# Generated by Django 5.0 on 2024-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0021_supplier_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_info',
            name='total_bags',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
