# Generated by Django 5.0 on 2024-04-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0022_cosmic_purchase_status_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplier_profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
