# Generated by Django 5.0 on 2024-05-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0022_cosmic_purchase_status_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmic_order',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
