# Generated by Django 5.0 on 2024-05-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0023_cosmic_order_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmic_purchase',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
